regions_abbr = {1:{"abbr":"RU-AD","official name":"Республика Адыгея","short":"Адыгея"},
2:{"abbr":"RU-BA","official name":"Республика Башкортостан","short":"Башкирия"},
3:{"abbr":"RU-BU","official name":"Республика Бурятия","short":"Бурятия"},
4:{"abbr":"RU-AL","official name":"Республика Алтай","short":"Алтай"},
5:{"abbr":"RU-DA","official name":"Республика Дагестан","short":"Дагестан"},
6:{"abbr":"RU-IN","official name":"Республика Ингушетия","short":"Ингушетия"},
7:{"abbr":"RU-KB","official name":"Кабардино-Балкарская Республика","short":"Кабардино-Балкария"},
8:{"abbr":"RU-KL","official name":"Республика Калмыкия","short":"Калмыкия"},
9:{"abbr":"RU-KC","official name":"Карачаево-Черкесская Республика","short":"Карачаево-Черкессия"},
10:{"abbr":"RU-KR","official name":"Республика Карелия","short":"Карелия"},
11:{"abbr":"RU-KO","official name":"Республика Коми","short":"Коми"},
12:{"abbr":"RU-ME","official name":"Республика Марий-Эл","short":"Марий Эл"},
13:{"abbr":"RU-MO","official name":"Республика Мордовия","short":"Мордовия"},
14:{"abbr":"RU-SA","official name":"Республика Саха-Якутия","short":"Якутия"},
15:{"abbr":"RU-SE","official name":"Республика Северная Осетия-Алания","short":"Северная Осетия"},
16:{"abbr":"RU-TA","official name":"Республика Татарстан","short":"Татарстан"},
17:{"abbr":"RU-TY","official name":"Республика Тува","short":"Тува"},
18:{"abbr":"RU-UD","official name":"Удмуртская Республика","short":"Удмуртия"},
19:{"abbr":"RU-KK","official name":"Республика Хакасия","short":"Хакасия"},
21:{"abbr":"RU-CU","official name":"Чувашская Республика","short":"Чувашия"},
22:{"abbr":"RU-ALT","official name":"Алтайский край"},
23:{"abbr":"RU-KDA","official name":"Краснодарский край"},
24:{"abbr":"RU-KYA","official name":"Красноярский край"},
25:{"abbr":"RU-PRI","official name":"Приморский край"},
26:{"abbr":"RU-STA","official name":"Ставропольский край"},
27:{"abbr":"RU-KHA","official name":"Хабаровский край"},
28:{"abbr":"RU-AMU","official name":"Амурская область"},
29:{"abbr":"RU-ARK","official name":"Архангельская область"},
30:{"abbr":"RU-AST","official name":"Астраханская область"},
31:{"abbr":"RU-BEL","official name":"Белгородская область"},
32:{"abbr":"RU-BRY","official name":"Брянская область"},
33:{"abbr":"RU-VLA","official name":"Владимирская область"},
34:{"abbr":"RU-VGG","official name":"Волгоградская область"},
35:{"abbr":"RU-VLG","official name":"Вологодская область"},
36:{"abbr":"RU-VOR","official name":"Воронежская область"},
37:{"abbr":"RU-IVA","official name":"Ивановская область"},
38:{"abbr":"RU-IRK","official name":"Иркутская область"},
39:{"abbr":"RU-KGD","official name":"Калининградская область"},
40:{"abbr":"RU-KLU","official name":"Калужская область"},
41:{"abbr":"RU-KAM","official name":"Камчатский край"},
42:{"abbr":"RU-KEM","official name":"Кемеровская область"},
43:{"abbr":"RU-KIR","official name":"Кировская область"},
44:{"abbr":"RU-KOS","official name":"Костромская область"},
45:{"abbr":"RU-KGN","official name":"Курганская область"},
46:{"abbr":"RU-KRS","official name":"Курская область"},
47:{"abbr":"RU-LEN","official name":"Ленинградская область"},
48:{"abbr":"RU-LIP","official name":"Липецкая область"},
49:{"abbr":"RU-MAG","official name":"Магаданская область"},
50:{"abbr":"RU-MOS","official name":"Московская область"},
51:{"abbr":"RU-MUR","official name":"Мурманская область"},
52:{"abbr":"RU-NIZ","official name":"Нижегородская область"},
53:{"abbr":"RU-NGR","official name":"Новгородская область"},
54:{"abbr":"RU-NVS","official name":"Новосибирская область"},
55:{"abbr":"RU-OMS","official name":"Омская область"},
56:{"abbr":"RU-ORE","official name":"Оренбургская область"},
57:{"abbr":"RU-ORL","official name":"Орловская область"},
58:{"abbr":"RU-PNZ","official name":"Пензенская область"},
59:{"abbr":"RU-PER","official name":"Пермский край"},
60:{"abbr":"RU-PSK","official name":"Псковская область"},
61:{"abbr":"RU-ROS","official name":"Ростовская область"},
62:{"abbr":"RU-RYA","official name":"Рязанская область"},
63:{"abbr":"RU-SAM","official name":"Самарская область"},
64:{"abbr":"RU-SAR","official name":"Саратовская область"},
65:{"abbr":"RU-SAK","official name":"Сахалинская область"},
66:{"abbr":"RU-SVE","official name":"Свердловская область"},
67:{"abbr":"RU-SMO","official name":"Смоленская область"},
68:{"abbr":"RU-TAM","official name":"Тамбовская область"},
69:{"abbr":"RU-TVE","official name":"Тверская область"},
70:{"abbr":"RU-TOM","official name":"Томская область"},
71:{"abbr":"RU-TUL","official name":"Тульская область"},
72:{"abbr":"RU-TYU","official name":"Тюменская область"},
73:{"abbr":"RU-ULY","official name":"Ульяновская область"},
74:{"abbr":"RU-CHE","official name":"Челябинская область"},
75:{"abbr":"RU-ZAB","official name":"Забайкальский край"},
76:{"abbr":"RU-YAR","official name":"Ярославская область"},
77:{"abbr":"RU-MOW","official name":"Москва"},
78:{"abbr":"RU-SPE","official name":"Санкт-Петербург"},
79:{"abbr":"RU-YEV","official name":"Еврейская автономная область"},
82:{"abbr":"RU-CR","official name":"Республика Крым","short":"Крым"},
91:{"abbr":"RU-CR","official name":"Республика Крым","short":"Крым"},
83:{"abbr":"RU-NEN","official name":"Ненецкий автономный округ"},
86:{"abbr":"RU-KHM","official name":"Ханты-Мансийский автономный округ"},
87:{"abbr":"RU-CHU","official name":"Чукотский автономный округ"},
89:{"abbr":"RU-YAN","official name":"Ямало-Ненецкий автономный округ"},
92:{"abbr":"RU-SEV","official name":"Севастополь"},
93:{"abbr":"RU-KDA","official name":"Краснодарский край"},
95:{"abbr":"RU-CE","official name":"Чеченская республика","short":"Чечня"},
20:{"abbr":"RU-CE","official name":"Чеченская республика","short":"Чечня"}
}